---
- name: Deploy Strapi
  hosts: api
  tags:
    - deploy
  vars:
    path: "/root/{{ dir }}"
  tasks:
    - name: Remove old containers
      ansible.builtin.shell: docker system prune -af
    - name: Creates directory
      file:
        path: "{{ path }}"
        state: directory
    - name: Copy Docker Compose
      copy:
        src: ./docker-compose.yml
        dest: "{{ path }}/docker-compose.yml"
    - name: Reload Compose
      community.general.docker_compose:
        pull: yes
        project_src: "{{ path }}"
