version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "4002:4002"
#    depends_on:
#      - database
    volumes:
      - ./api:/api
      - /api/node_modules
    command: npm start -V
    working_dir: /api

  backend:
    build: ./backend
    ports:
      - "3000:3000"
#    environment:
#      MONGO_URL: mongodb://host.docker.internal:27017/bookcars
    depends_on:
      - api
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    command: npm start -V
    working_dir: /backend
    links:
      - api:api

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - api
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules

    command: npm start -V
    working_dir: /frontend
    links:
      - api:api


# missing static hosting for images

#  database:
#    image: mongo:latest
#    expose:
#      - "27017"
#    restart: always
