services:
  bc-mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  bc-mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@bc-mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    healthcheck:
      test: ["CMD", "mongo", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - bc-mongo

  bc-dev-api:
    build:
      context: .
      dockerfile: ./api/Dockerfile.dev
    env_file: ./api/.env.docker
    restart: always
    ports:
      - 4002:4002
    depends_on:
      - bc-mongo
    volumes:
      - cdn:/var/www/cdn/bookcars
      - ./api:/bookcars/api
      - api_node_modules:/bookcars/api/node_modules

  bc-dev-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    env_file: ./backend/.env.docker
    restart: always
    depends_on:
      - bc-dev-api
    ports:
      - 3001:3001
    volumes:
      - ./backend:/bookcars/backend
      - backend_node_modules:/bookcars/backend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

  bc-dev-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    env_file: ./frontend/.env.docker
    restart: always
    depends_on:
      - bc-dev-api
    ports:
      - 8080:8080
      - 8443:443
    volumes:
      - ./frontend:/bookcars/frontend
      - frontend_node_modules:/bookcars/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  cdn:
  api_node_modules:
  backend_node_modules:
  frontend_node_modules:
  mongodb_data:
  mongodb_config:
